<!-- ContactHubJs -->
<?php if($this->isJsTrackingEnabled()): ?>
<script>
window.ch=function(){(ch.q=ch.q||[]).push(arguments)};
<?php /* @escapeNotVerified */ echo $this->getConfigData(); ?>
<?php /* @escapeNotVerified */ echo $this->getEventData(); ?>
</script>
<script async src='https://assets.contactlab.it/contacthub/sdk-browser/latest/contacthub.min.js'></script>
<?php else: ?>
<!-- Js Tracking Is Disabled -->
<?php endif; ?>
<!-- END ContactHubJs -->
